import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {

  const minutes = 25;
  const seconds = "00";

  function template() {
    document.getElementById("min").innerHTML = minutes;
    document.getElementById("sec").innerHTML = seconds;
  }

  function start() {
    document.getElementById("click").play();

    minutes = 24;
    seconds = 59;

    document.getElementById("min").innerHTML = minutes;
    document.getElementById("sec").innerHTML = seconds;

    const m_interval = setInterval(minutesTimer, 60000);
    const s_interval = setInterval(secondsTimer, 1000);

    function minutesTimer() {
      minutes = minutes - 1;
      document.getElementById("min").innerHTML = minutes;
    }

    function secondsTimer() {
      seconds = seconds - 1;
      document.getElementById("sec").innerHTML = seconds;

      if (seconds <= 0) {
        if (minutes <= 0) {
          clearInterval(m_interval);
          clearInterval(s_interval);

          document.getElementById("end").play();
        }
        seconds = 60;
      }
    }
  }

  return (
    <div className={styles.container} onLoad={template}>
      <Head>
        <title>Pomodoro</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Pomodoro.png" />
      </Head>
      
      <header className={styles.header}>
          <h1 className={styles.title}>
            Welcome to Pomodoro Timer
          </h1>
      </header>

      <main className={styles.main}>
        <section className={styles.mainPomodoro}>
          <div>
            <ul>
              <li><span>Pomodoro</span></li>
              <li><span>Short break</span></li>
              <li><span>Long break</span></li>
            </ul>
          </div>

          <div className={styles.timer}>
            <div>
              <h4 id="min"></h4>
            </div>
            <div>
              <h4> : </h4>
            </div>
            <div>
              <h4 id="sec"></h4>
            </div>
          </div>

          <div className={styles.btnGroup}>
            <button className={styles.start} onClick={start}>
              <span>Start / Stop</span>
              <audio id="click" src="click.mp3"></audio>
              <audio id="end" src="end.mp3"></audio>
            </button>
            <button className={styles.reset}><span>Reset</span></button>
          </div>
        </section>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://www.linkedin.com/in/ronaldeived/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by Ronaldeived
        </a>
      </footer>
    </div>
  )
}
